### ISSUE TITLE
.exe Does not open

### ISSUE THREAD

**Issue by notcarksss** [SirJosh3917/EMakesAlts#1]
It says EMakesAlts.exe has stopped working, and when i try to run it with Visual Studio,
it says this: "IOException not handled"

**Comment by monoclex** [comment]
What line of the IO.cs file does it throw it on?

**Comment by monoclex** [comment]
Turns out it had to do with IO.cs not being fully functional as I thought.
I fixed it a bit, so this is no longer an issue.
